server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: cn-oalo-admin
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cn_oalo?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      max-evictable-idle-time-millis: 900000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: 123456
  redis:
    host: 111.229.149.99
    port: 6379
    password: DM27NPKemdX3sBYB
    database: 0
    timeout: 10s
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: cn.oalo.**.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0

jwt:
  secret: 54d78ee76ef42c54d78ee76ef42c54d78ee76ef42c54d78ee76ef42c
  expiration: 86400

swagger:
  enabled: true
  title: OALO API文档
  description: OALO API文档
  version: 1.0.0
  contact:
    name: cR
    url: https://blog.oalo.cn
    email: admin@oalo.cn

# 日志配置
logging:
  level:
    cn.oalo: debug
    org.springframework: warn

# 文件上传配置
file:
  upload:
    # 上传路径
    path: upload
    # 允许的文件类型
    allowed-types: .jpg,.jpeg,.png,.gif,.bmp,.doc,.docx,.xls,.xlsx,.ppt,.pptx,.pdf,.txt,.zip,.rar,.gz,.7z,.mp3,.mp4,.avi,.rmvb
    # 允许的最大文件大小（单位：MB）
    max-size: 10
  # 文件存储类型（LOCAL本地 ALIYUN_OSS阿里云 TENCENT_COS腾讯云 QINIU_KODO七牛云 MINIO）
  storage:
    type: LOCAL
# 阿里云OSS配置
oss:
  # 访问域名
  endpoint: oss-cn-beijing.aliyuncs.com
  # 访问身份ID
  accessKeyId: your-access-key-id
  # 访问身份密钥
  accessKeySecret: your-access-key-secret
  # 存储空间名称
  bucketName: your-bucket-name
  # 自定义域名（可选）
  domain: https://your-bucket-name.oss-cn-beijing.aliyuncs.com 