server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: enterprise-app
  datasource:
    dynamic:
      primary: master # 设置默认数据源
      strict: false # 严格匹配数据源，默认false，true未匹配到指定数据源时抛异常
      datasource:
        master: # 主数据源
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/enterprise_app?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
          username: root
          password: root
          type: com.alibaba.druid.pool.DruidDataSource
        slave: # 从数据源
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/enterprise_app_slave?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
          username: root
          password: root
          type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 2000
        wall:
          enabled: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: 123456
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
    timeout: 60000
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 8
        min-idle: 0

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: cn.oalo.domain.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_null
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  level:
    root: info
    cn.oalo: debug

jwt:
  secret: 54d78ee76ef42c54d78ee76ef42c54d78ee76ef42c54d78ee76ef42c
  expiration: 86400  # 1天，单位：秒

swagger:
  enabled: true
  title: ${spring.application.name}
  description: 企业级应用框架API文档
  version: 1.0.0
  contact:
    name: OALO
    url: https://oalo.cn
    email: contact@oalo.cn

# 阿里云OSS配置
aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    accessKeyId: your-access-key-id
    accessKeySecret: your-access-key-secret
    bucketName: your-bucket-name
    domain: https://your-bucket-name.oss-cn-beijing.aliyuncs.com 